max_word_length: 100000
datasets:
  dataset7:
    url: "https://mindguard.s3.amazonaws.com/raw/cyberbullying_tweets.tsv"
    proportion_with_feature: 1
    proportion_neutral: 0
    feature_column: "cyberbullying_type"
    text_column: "tweet_text"
    feature_presence_tags: ["religion", "age", "gender", "ethnicity", "other_cyberbullying"]
    category: 3
    label: "cyber_bullying"
