max_word_length: 100000
datasets:
  dataset5:
    url: "https://mindguard.s3.amazonaws.com/raw/mental-health.tsv"
    proportion_with_feature: 1
    proportion_neutral: 0
    feature_column: "label"
    text_column: "text"
    feature_presence_tags: ["SuicideWatch"]
    category: 2
    label: "suicidal_ideation"
  dataset6:
    url: "https://mindguard.s3.amazonaws.com/raw/Suicide_Ideation_Datase_Twitter_based.tsv"
    proportion_with_feature: 1
    proportion_neutral: 0
    feature_column: "Suicide"
    text_column: "Tweet"
    feature_presence_tags: ["Potential Suicide post"]
    category: 2
    label: "suicidal_ideation"
