datasets:
  dataset1:
    url: "https://djtoroelab1.s3.amazonaws.com/cyberbullying_tweets.csv"
    proportion_with_feature: 0.7
    proportion_neutral: 0.0
    feature_column: "cyberbullying_type"
    text_column: "tweet_text"
    feature_presence_tags: ["religion", "age", "gender", "ethnicity"]
    category: 2
  dataset2:
    url: "https://mind-guard.s3.amazonaws.com/sentiment_tweets3.csv"
    proportion_with_feature: 0.0
    proportion_neutral: 0.0
    feature_column: "label (depression result)"
    text_column: "message to examine"
    feature_presence_tags: [1]
    category: 1
  dataset3:
    url: "https://mind-guard.s3.amazonaws.com/StudentsAnxietyAndDepression.csv"
    proportion_with_feature: 0.0
    proportion_neutral: 0.0
    feature_column: "label"
    text_column: "text"
    feature_presence_tags: [1]
    category: 1
