datasets:
  dataset1:
    url: "https://djtoroelab1.s3.amazonaws.com/cyberbullying_tweets.csv"
    proportion_with_feature: 0.7
    proportion_neutral: 0.15
    feature_column: "cyberbullying_type"
    text_column: "tweet_text"
    feature_presence_tags: ["religion", "age", "gender", "ethnicity"]
    category: 1
    tag_category: "Cyberbullying"
  dataset2:
    url: "https://mind-guard.s3.amazonaws.com/StudentsAnxietyAndDepression.csv"
    proportion_with_feature: 0.8
    proportion_neutral: 0.15
    feature_column: "label"
    text_column: "text"
    feature_presence_tags: [1]
    category: 2
    tag_category: "Depression & Anxiety"
  dataset3:
    url: "https://mind-guard.s3.amazonaws.com/Suicide_Ideation_Dataset(Twitter-based).csv"
    proportion_with_feature: 1
    proportion_neutral: 0.15
    feature_column: "Suicide"
    text_column: "Tweet"
    feature_presence_tags: ["Potential Suicide post"]
    category: 3
    tag_category: "Suicidal ideation"